---
abstract: 'A Path::Class type library for Mouse'
author:
  - 'NAKAGAWA Masaki <masaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.94
  Test::UseAllModules: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MouseX-Types-Path-Class
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  MouseX::Getopt: 0.2200
requires:
  Mouse: 0.39
  MouseX::Types: 0.02
  Path::Class: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
